apiVersion: v1
kind: Service
metadata:
  name: hootcache
  labels:
    app: hootcache
spec:
  type: NodePort
  ports:
    - nodePort: 32000
      name: "32000"
      port: 32000
      targetPort: 5000
  selector:
    app: hootcache
